name: Migration Tool (Build and draft release)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        targetplatform: [x64]
        ChannelName: [Release]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore dependencies
        run: dotnet restore "source/MigrationTool/MigrationTool.csproj"

      - name: Test
        run: dotnet test "source/MigrationTool/MigrationTool.csproj"

      - name: Release Build MigrationTool
        run: dotnet publish -c Release -r win-x64 --self-contained false -p:DebugType=none /p:PublishSingleFile=true -o publish "source/MigrationTool/MigrationTool.csproj"

      - name: Package
        run: |
          $exe = Get-ChildItem -Path .\publish\*.exe | Select-Object -First 1
          Compress-Archive -Path $exe.FullName -DestinationPath .\migration-tool.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: migration-tool
          path: ./migration-tool.zip

      - name: Create new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "new-migraiton-build"
          release_name: New Migration-Tool Build
          draft: true

      - name: Upload release asset
        id: upload_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./migration-tool.zip
          asset_name: migration-tool.zip
          asset_content_type: application/zip
